const data = {
  "kitchen_item": {
          "Salt": 1.0,
          "Pepper": 0.5,
          "Turmeric": 0.2,
          "Cumin": 0.2,
          "Coriander": 0.2,
          "Chili Powder": 0.2,
          "Paprika": 0.2,
          "Kitchen King": 0.2,
          "Chole Masala": 0.2,
          "Chat Masala": 0.2,
          "Mutton Masala": 0.2,
          "Biryani Masala": 0.2,
          "Garam Masala": 0.2,
          "Cardamom": 0.1,
          "Cloves": 0.1,
          "Cinnamon": 0.1,
          "Fenugreek": 0.1,
          "Mustard Seeds": 0.1,
          "Asafoetida": 0.05,
          "Bay Leaves": 0.1,
          "Black Peppercorns": 0.1,
          "Fish": 2.0,
          "Chicken": 3.0,
          "Mutton": 2.5,
          "Paneer":2,
          "Mango": 2.0,
          "Banana": 1.5,
          "Apple": 1.0,
          "Orange": 1.5,
          "Papaya": 2.0,
          "Guava": 1.5,
          "Pomegranate": 1.0,
          "Grapes": 1.5,
          "Pineapple": 1.5,
          "Watermelon": 3.0,
          "Potato": 3.0,
          "Onion": 2.5,
          "Tomato": 2.0,
          "Cauliflower": 1.5,
          "Spinach": 1.0,
          "Carrot": 1.5,
          "Cabbage": 1.5,
          "Bell Pepper": 1.0,
          "Eggplant": 1.0,
          "Peas": 1.0,
          "Okra": 1.0,
          "Bitter Gourd": 1.0,
          "Pumpkin": 1.5,
          "Butter": 1.0,
          "Ghee": 1.0,
          "Saucepan": 1,
          "Frying Pan": 1,
          "Stockpot": 1,
          "Pressure Cooker": 1,
          "Dutch Oven": 1,
          "Wok": 1,
          "Kadhai": 1,
          "Tawa": 1,
          "Microwave": 1,
          "Induction Cooktop": 1,
          "Blender": 1,
          "Toaster": 1,
          "Oven": 1
  }
};

export {data};